#!/bin/sh
mv /etc/enigma2/moviecockpit.db /etc/enigma2/moviecockpit.db.bak
touch /tmp/.moviecockpit

echo "***********************************"
echo "*          MovieCockpit           *"
echo "*               by                *"
echo "*          dream-alpha            *"
echo "***********************************"
echo ""
echo "Plugin MovieCockpit installed successfully."
echo "Please restart DreamOS now!"
echo ""
exit 0
